es:
  image: elasticsearch:1.4.4
  volumes:
    - ./config:/data/config
  volumes_from:
    - data
  ports: 
    - 9200
  command: /elasticsearch/bin/elasticsearch -Des.config=/data/config/elasticsearch.yml
data:
  image: ubuntu 
  volumes:
    - /data/logs
    - /data/data
    - /data/plugins
  command: /bin/bash
