version: '2.0'
services:
  dbao-elasticsearch-master:
    image: elasticsearch:5.2.0
    command: "elasticsearch -Enode.master=true -Enode.data=false"
    environment:
      - ES_JAVA_OPTS=-Xmx1g -Xms1g
    ports:
      - "9200:9200"
      - "9300:9300"
    privileged: true
#    sysctls:
#      - vm.max_map_count=262144

  dbao-elasticsearch-slave:
    image: elasticsearch:5.2.0
    command: "elasticsearch -Ediscovery.zen.ping.unicast.hosts=dbao-elasticsearch-master"
    environment:
      - ES_JAVA_OPTS=-Xmx1g -Xms1g
    links:
      - dbao-elasticsearch-master
    privileged: true

#    sysctls:
#      - vm.max_map_count=262144

  dbao-kibana:
    image: kibana:5.2.0
    ports:
      - "5601:5601"
    links:
      - dbao-elasticsearch-master:elasticsearch

  dbao-elasticsearch-head:
    image: mobz/elasticsearch-head:5
    ports:
      - "9100:9100"
    links:
      - dbao-elasticsearch-master
